// examples/bun-solid/src/Counter.tsx
import { createSignal } from 'solid-js'

export function Counter() {
  const [count, setCount] = createSignal(0)

  function increment() {
    setCount(count() + 1)
  };

  function decrement() {
    setCount(count() - 1)
  };

  return (
    <div>
      <h1>Counter</h1>
      <div>Count: {count()}</div>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  )
}

// examples/vitest-react/components/Counter.tsx
import React, { useState } from 'react'

export function Counter() {
  const [count, setCount] = useState(0)

  function increment() {
    setCount(c => c + 1)
  };

  function decrement() {
    setCount(c => c - 1)
  };

  return (
    <div className="counter-app">
      <h1>Counter</h1>
      <p>Count: {count}</p>
      <button onClick={increment} className="green-button">Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  )
}
